
    <article class="creation">
        <h2><i class="fa fa-user" aria-hidden="true"></i> Création d'un compte client</h2>
        <form method="POST" action="<?= $requestUrl?>/creation">
            <fieldset>
                <legend>Vos coordonnées</legend>
            <input type="text" name="lastname" placeholder="Votre nom">
            <input type="text" name="firstname" placeholder="Votre prénom"><br>
            <input type="text" name="adress" placeholder="Votre adresse" size="50"><br>
            <input type="tel" name="tel" placeholder="Votre téléphone">
            </fieldset>
            <fieldset>
                <legend>Informations d'authentification</legend>
            <input type="email" id="login" name="login" placeholder="Votre adresse e-mail"><br>
            <input type="password" name="password" placeholder="Votre mot de passe"><br>
            <input type="submit" name="submit" id="run">
            </fieldset>

        </form>
    </article>
